"""Stub patch synthesis.

Given a classified error event, propose a minimal source-code patch that
would silence the error long enough for the operator to provide a real
implementation. We bias hard toward *safe noise*: every synth output is
a ``NotImplementedError`` body with an explanatory docstring -- never a
silent ``return None``. Reviewing operators see exactly which symbol
needs filling in.

Output shape -- ``StubPatch``:

* ``target_path``    -- repo-relative path the patch would touch
                        (may not exist yet for IMPORT_ERROR)
* ``mode``           -- ``"new_file"`` | ``"append_method"`` |
                        ``"append_function"``
* ``symbol``         -- the symbol name being stubbed
* ``snippet``        -- the literal code to insert
* ``rationale``      -- one-line operator-facing explanation

We do *not* execute the patch -- the PR builder (or the dry-run CLI)
turns the snippet into a unified diff. This keeps synth pure and
trivially testable.
"""
from __future__ import annotations

import re
from dataclasses import dataclass

from packages.healing.classifier import ErrorCategory, is_patchable
from packages.healing.error_capture import ErrorEvent

# AttributeError("'Foo' object has no attribute 'bar'")
_ATTR_PATTERN = re.compile(
    r"'([\w.]+)'\s+object\s+has\s+no\s+attribute\s+'(\w+)'"
)
# ModuleNotFoundError: No module named 'packages.foo'
_IMPORT_PATTERN = re.compile(r"No module named ['\"]([\w.]+)['\"]")
# NotImplementedError: foo.bar.Quux.method
_NOTIMPL_QUAL = re.compile(r"([\w.]+)$")


@dataclass(frozen=True)
class StubPatch:
    target_path: str
    mode: str  # "new_file" | "append_method" | "append_function"
    symbol: str
    snippet: str
    rationale: str


def _path_for_module(module: str) -> str:
    """Convert ``packages.foo.bar`` -> ``packages/foo/bar.py`` (relative)."""
    return module.replace(".", "/") + ".py"


def _new_module_snippet(module: str) -> str:
    return (
        f'"""Auto-stubbed module ``{module}``.\n\n'
        f"Generated by packages.healing.stub_synth. Replace this stub with the\n"
        f'real implementation before merging.\n"""\n'
        f"from __future__ import annotations\n\n\n"
        f"def _todo() -> None:\n"
        f'    raise NotImplementedError("module {module} is an auto-generated stub")\n'
    )


def _new_method_snippet(symbol: str) -> str:
    return (
        f"\n    def {symbol}(self, *args, **kwargs):\n"
        f'        """Auto-stub for ``{symbol}``.\n\n'
        f"        Generated by packages.healing.stub_synth in response to a\n"
        f"        captured AttributeError. Replace with a real implementation.\n"
        f'        """\n'
        f'        raise NotImplementedError("{symbol} is an auto-generated stub")\n'
    )


def _new_function_snippet(symbol: str) -> str:
    return (
        f"\n\ndef {symbol}(*args, **kwargs):\n"
        f'    """Auto-stub for ``{symbol}``. Replace before merging."""\n'
        f'    raise NotImplementedError("{symbol} is an auto-generated stub")\n'
    )


def _from_attribute_error(event: ErrorEvent) -> StubPatch | None:
    m = _ATTR_PATTERN.search(event.exc_message)
    if not m:
        return None
    qualified, attr = m.group(1), m.group(2)
    # Try to walk the traceback for a packages.* module hint.
    module_hint = _module_from_traceback(event.traceback)
    if not module_hint:
        return None
    return StubPatch(
        target_path=module_hint,
        mode="append_method",
        symbol=attr,
        snippet=_new_method_snippet(attr),
        rationale=(
            f"AttributeError on {qualified}.{attr} -- proposing a stub method "
            f"on the same module."
        ),
    )


def _from_import_error(event: ErrorEvent) -> StubPatch | None:
    m = _IMPORT_PATTERN.search(event.exc_message)
    if not m:
        return None
    module = m.group(1)
    if not module.startswith("packages."):
        return None
    return StubPatch(
        target_path=_path_for_module(module),
        mode="new_file",
        symbol=module,
        snippet=_new_module_snippet(module),
        rationale=f"ModuleNotFoundError for first-party module {module}.",
    )


def _from_not_implemented(event: ErrorEvent) -> StubPatch | None:
    # NotImplementedError is *already* a stub of sorts -- the operator
    # asked for it. We surface the symbol so the PR description can
    # point at it, but we do not propose source changes.
    msg = event.exc_message.strip()
    sym = "<unknown>"
    if msg:
        m = _NOTIMPL_QUAL.search(msg)
        if m:
            sym = m.group(1)
    module_hint = _module_from_traceback(event.traceback) or "<unknown>"
    return StubPatch(
        target_path=module_hint,
        mode="append_function",
        symbol=sym,
        snippet=_new_function_snippet(sym) if sym != "<unknown>" else "",
        rationale=(
            "NotImplementedError raised -- surfacing the symbol so a human "
            "can fill in the real implementation."
        ),
    )


def _module_from_traceback(tb: str) -> str | None:
    # Look for a 'File "/.../packages/foo/bar.py"' line.
    for line in tb.splitlines():
        line = line.strip()
        if not line.startswith("File "):
            continue
        m = re.search(r'File "([^"]+packages[/\\][^"]+\.py)"', line)
        if not m:
            continue
        path = m.group(1).replace("\\", "/")
        idx = path.rfind("packages/")
        if idx == -1:
            continue
        return path[idx:]
    return None


def synthesize_stub(event: ErrorEvent, category: ErrorCategory) -> StubPatch | None:
    """Return a proposed stub patch, or ``None`` if not patchable."""
    if not is_patchable(category):
        return None
    if category is ErrorCategory.MISSING_STUB:
        return _from_not_implemented(event)
    if category is ErrorCategory.ATTRIBUTE_ERROR:
        return _from_attribute_error(event)
    if category is ErrorCategory.IMPORT_ERROR:
        return _from_import_error(event)
    return None
